client.insert = INSERT INTO flowershop.client (first_name, last_name, middle_name, email, phone) VALUES(?, ?, ?, ?, ?)
client.update = UPDATE flowershop.client SET first_name=?, last_name=?, middle_name=?, email=?, phone=? WHERE client_id = ?
client.delete = DELETE FROM flowershop.client WHERE client_id = ?
client.select = SELECT * FROM flowershop.client
client.find = SELECT * FROM flowershop.find_client(?, ?, ?)

bouquet.insert = INSERT INTO flowershop.bouquet (name, price, description) VALUES (?, ?, ?) RETURNING bouquet_id
bouquet.update = UPDATE flowershop.bouquet SET name = ?, price = ?, description = ? WHERE bouquet_id = ?
bouquet.delete = DELETE FROM flowershop.bouquet WHERE bouquet_id = ?
bouquet.select = SELECT * FROM flowershop.bouquet
bouquet.find = SELECT * FROM flowershop.find_bouquet(?, ?, ?)

flowers.insert = INSERT INTO flowershop.flowers (name, price, quantity, img_path) VALUES (?, ?, ?, ?)
flowers.update = UPDATE flowershop.flowers SET name = ?, price = ?, quantity = ?, img_path = ? WHERE flower_id = ?
flowers.delete = DELETE FROM flowershop.flowers WHERE flower_id = ?
flowers.select = SELECT * FROM flowershop.flowers
flowers.find = SELECT * FROM flowershop.find_flowers(?, ?::numeric, ?::numeric)
flowers.updateQuantity = UPDATE flowershop.flowers SET quantity = quantity + ? WHERE flower_id = ?

bouquet_composition.insert = INSERT INTO flowershop.bouquet_composition (bouquet_id, flower_id, quantity, price) VALUES (?, ?, ?, ?)
bouquet_composition.select = SELECT bc.bouquet_id, bc.flower_id, bc.quantity AS composition_quantity, bc.price AS composition_price, f.name, f.price AS flower_price, f.quantity AS flower_quantity, f.img_path FROM flowershop.bouquet_composition bc JOIN flowershop.flowers f ON bc.flower_id = f.flower_id WHERE bc.bouquet_id = ?
bouquet_composition.delete = DELETE FROM flowershop.bouquet_composition WHERE bouquet_id = ?
bouquet_composition.update = UPDATE flowershop.bouquet_composition SET quantity = ?, price = ? WHERE bouquet_id = ?

florist.select = SELECT * FROM flowershop.florist

delivery.insert = INSERT INTO flowershop.delivery (flower_id, quantity, date) VALUES (?, ?, ?)

address.insert = INSERT INTO flowershop.address (city, street, house, entrance) VALUES (?, ?, ?, ?) RETURNING address_id
address.select = SELECT * FROM flowershop.address
address.update = UPDATE flowershop.address SET city = ?, street = ?, house = ?, entrance = ? WHERE address_id = ?

order.create = SELECT flowershop.create_order(?, ?, ?, ?, ?, ?, ?)
order.get_all = SELECT * FROM flowershop.get_orders()
order.find = SELECT * FROM flowershop.find_order (?, ?, ?, ?)

